# arxivの学問領域の指定
subject: 'cat:cs.*'

# 検索キーワード
keywords:
        sports: 3
        human action: 3
        similarity: 3
        human motion: 3
        body movement: 3
        neural network: 2
        deep learning: 2
        skeleton: 2
        metric learning: 2
        gait: 1
        MLP: 1
        

# 通知の閾値
score_threshold: 3
